#!/usr/bin/env node
var log = console.log

var flat =  require('./flat')

//var r =  flat.parse("cat [ -ul cat dog d cat[u dog dr cat] ]")
//var r =  flat.parse("cat [ u cat dog cat dog  ]")
//var r =  flat.parse("u cat dog cat dog")
var str = `cat[ u dog[u  dog] ]`

log(str)
var r =  flat.parse(str)
log(JSON.stringify(r, null, '\t'))