#!/usr/bin/env node

var fs 				= require('fs')
var glob 			= require('./js/app/orthoGlobals')
var orthoRender 	= require('./js/app/orthoRender')
var lib 			= require('./js/orthoLib')
var svgRender 		= require("./js/svgRender")
var log=console.log

if (process.argv.length===2){
	console.log("USAGE: bin2json INPUT [OUTPUT]")
	return
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i]
	if (inputFileName===""){
		inputFileName=t
	} else if (outputFileName===""){
		outputFileName=t
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".")		
	}
}

if (inputFileName=="")
{
	console.log("need to supply input file")
}

if (outputFileName===""){

	var path = require('path');
	var globalPath = path.resolve(inputFileName)
	var parsed = path.parse(globalPath)
	parsed.ext=".json"
	parsed.dir+="/../json"
	parsed.base=parsed.name+"_b"+parsed.ext;
	outputFileName = path.format(parsed)
	log("outputFileName = "+outputFileName)
}

lib.loadBinary(inputFileName)

lib.saveFile(outputFileName)
log("saved " + outputFileName)
