#!/usr/bin/env node

var fs = require('fs')
eval(fs.readFileSync('../ortho/www/js/orthoGlobals.js')+'')
eval(fs.readFileSync('../ortho/www/js/orthoRender.js')+'')
eval(fs.readFileSync('js/orthoLib.js')+'')
eval(fs.readFileSync('js/orthoTopology.js')+'')


if (process.argv.length===2){
	console.log("USAGE: json2bin INPUT [OUTPUT]")
	return
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i]
	if (inputFileName===""){
		inputFileName=t
	} else if (outputFileName===""){
		outputFileName=t
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".")		
	}
}

if (inputFileName=="")
{
	console.log("need to supply input file")
}

if (outputFileName===""){

	var path = require('path');
	var globalPath = path.resolve(inputFileName)
	var parsed = path.parse(globalPath)
	parsed.ext=".bin"
	parsed.dir+="/../bin"
	parsed.base=parsed.name+parsed.ext;
	outputFileName = path.format(parsed)
	log("outputFileName = "+outputFileName)
}

loadFile(inputFileName)

saveBinary(outputFileName)
log("saved " + outputFileName)