#!/usr/bin/env node
var fs = require('fs')
log = console.log

var glob = require('../ortho/www/js/orthoGlobals')
var lib = require('./js/orthoLib')
var svgRender = require("./js/svgRender")

if (process.argv.length===2){
	console.log("USAGE: json2svg [-noGridLines] [-diagonals] [-noIcons] [-noLines] FILENAME [OUTPUT]");
	return;
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i];
	if (t==="-noGridLines"){
		drawGridLines=false;
	} else if (t==="-diagonals"){
		drawGridLines_Diagonal=true;
	} else if (t==="-noIcons"){
		drawElements=false;
	} else if (t==="-noLines"){
		drawLines=false;
	} else if (t==="-selectiveGridLines"){
		drawSelectiveGridLines=true;
	} else if (inputFileName===""){
		inputFileName=t;
		console.log("input file "+t)
	} else if (outputFileName===""){
		outputFileName=t;
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".");		
	}
}

if (inputFileName=="")
{
	console.log("need to supply input file");
}

if (outputFileName===""){

	var path = require('path');
	var globalPath = path.resolve(inputFileName)
	var parsed = path.parse(globalPath)
	parsed.ext=".svg"
	parsed.dir+="/../svg"
	parsed.base=parsed.name+parsed.ext;
	outputFileName = path.format(parsed)
	log("outputFileName = "+outputFileName)
}

lib.loadFile(inputFileName);


var canvasDimensions = lib.canvasSize();

lib.setOffsetToTopLeft();

var Canvas = require('canvas')
var Image = Canvas.Image

canvas = new Canvas(canvasDimensions[0], canvasDimensions[1])
ctx = canvas.getContext('2d');

var svgDat = svgRender();
fs.writeFileSync(outputFileName, svgDat);
console.log("generated "+ outputFileName);
