#!/usr/bin/env node

var fs = require('fs')
eval(fs.readFileSync('../ortho/www/js/orthoGlobals.js')+'')
eval(fs.readFileSync('../ortho/www/js/orthoRender.js')+'')
eval(fs.readFileSync('js/orthoLib.js')+'')
eval(fs.readFileSync('js/orthoTopology.js')+'')

if (process.argv.length===2){
	console.log("USAGE: drawOrtho [-noGridLines] [-diagonals] [-noIcons] [-noLines] FILENAME [OUTPUT]");
	return;
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i];
	if (t==="-noGridLines"){
		drawGridLines=false;
	} else if (t==="-diagonals"){
		drawGridLines_Diagonal=true;
	} else if (t==="-noIcons"){
		drawElements=false;
	} else if (t==="-noLines"){
		drawLines=false;
	} else if (t==="-selectiveGridLines"){
		drawSelectiveGridLines=true;
	} else if (inputFileName===""){
		inputFileName=t;
		console.log("input file "+t)
	} else if (outputFileName===""){
		outputFileName=t;
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".");		
	}
}

if (inputFileName=="")
{
	console.log("need to supply input file");
}

if (outputFileName===""){

	var path = require('path');
	var globalPath = path.resolve(inputFileName)
	var parsed = path.parse(globalPath)
	parsed.ext=".png"
	parsed.dir+="/../png"
	parsed.base=parsed.name+parsed.ext;
	outputFileName = path.format(parsed)
	log("outputFileName = "+outputFileName)
}

loadFile(inputFileName);


var canvasDimensions = canvasSize();

setOffsetToTopLeft();

var Canvas = require('canvas')
var Image = Canvas.Image

canvas = new Canvas(canvasDimensions[0], canvasDimensions[1])
ctx = canvas.getContext('2d');

orthoRender();

var dataURL = canvas.toDataURL();
var data = dataURL.replace(/^data:image\/\w+;base64,/, "");
var buf = new Buffer(data, 'base64');
fs.writeFile(outputFileName, buf);
console.log("generated "+ outputFileName);
