#!/usr/bin/env node

var fs 				= require('fs')
var glob 			= require('./js/orthoGlobals')
var canvasRender 	= require('./js/canvasRender')
var lib 			= require('./js/orthoLib')
var svgRender 		= require("./js/svgRender")

var log=console.log

if (process.argv.length===2){
	console.log("USAGE: reduce INPUT [OUTPUT]")
	return
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i]
	if (inputFileName===""){
		inputFileName=t
	} else if (outputFileName===""){
		outputFileName=t
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".")		
	}
}

if (inputFileName==="")
{
	console.log("need to supply input file")
}

if (outputFileName===""){
	var path = require('path');
	var globalPath = path.resolve(inputFileName)
	var parsed = path.parse(globalPath)
	parsed.ext=".json"
	//parsed.dir+="/../bin"
	parsed.base=parsed.name+"_contracted"+parsed.ext;
	outputFileName = path.format(parsed)
	log("outputFileName = "+outputFileName)
}




function Relativize(){
	var page=glob.page;
	var elements=[]
	for (var i=0;i<page.elements.length;i++){
		elements.push(page.elements[i][2])
	}
	var lines=[];
	for(var i=0;i<page.lines.length;i++){
		var l = page.lines[i];
		var e_i1 = lib.getIconIndexAt(l[0],l[1])
		var e_i2 = lib.getIconIndexAt(l[2],l[3])
		var lt = l[4]
		var ll = lib.LineLength(l)
		var ld = lib.LineDirection(l)
		lines.push([e_i1,e_i2,ld,lt,ll])
	}
	var result = {
		elements:elements,
		lines:lines
	};
	return result
}

function Absolutize(dat){
	var r_elements=dat.elements;
	var r_lines = dat.lines;

	var visited_elems=[0]
	var visited_lines=[]

	var elements=[ [0, 0, 0 ] ]
	var lines=[]
	while (lines.length<r_lines.length){
		for (var i=0;i<r_lines.length;i++){
			if (visited_lines.indexOf(i)>=0){
				continue;
			}
			var l = r_lines[i]
			var ld = l[2]
			var lt = l[3]
			var ll = l[4]
			for (var j=0;j<elements.length;j++){
				var e = elements[j]
				var et=e[2]
				if (et===l[0]||et===l[1]){
					var e_o=l[1];
					if (et===l[1]){
						ld=-ld;
						e_o=l[0]
					}
					var [dx,dy]=lib.axes[ld]
					var nx = e[0]+ll*dx;
					var ny = e[1]+ll*dy;
					visited_lines.push(i);
					visited_elems.push(j);
					elements.push([nx,ny,e_o])
					// log("pushing "+elements[elements.length-1])
					lines.push([e[0],e[1],nx,ny,lt])
					break;
				}
			}
		}
	}
	// log("ELEMENTS "+elements)
	// log("visited_elems "+visited_elems)
	//dont' forget to replace the line type with the actual line type here
	for (var i=0;i<elements.length;i++){
		var e = elements[i]
		e[2]=r_elements[e[2]]
	}
	glob.page.elements=elements;
	glob.page.lines=lines;
}

function Reduce(){
	var start = Relativize();

	var reduced=true;
	while(reduced){
		reduced=false;
		for (var i=0;i<start.lines.length;i++){
			var l = start.lines[i];
			l[4]--;			
			Absolutize(start);
			if (lib.SelfIntersects()){
				l[4]++;
			} else {
				reduced=true;
			}
		}
	}
	Absolutize(start);
}


lib.loadFile(inputFileName)
Reduce();
lib.saveFile(outputFileName)
log("saved " + outputFileName)
