#!/usr/bin/env node

var fs 				= require('fs')

/*
[{"elements":[[11,6,0],[10,5,11]],"lines":[[11,6,10,5,0]],"offsetX":0,"offsetY":0,"scale":1,"sketchTitle":""}]
*/

var scrapbook = [];

function ar_shuffle(a) {
    for (let i = a.length; i; i--) {
        let j = Math.floor(Math.random() * i);
        [a[i - 1], a[j]] = [a[j], a[i - 1]];
    }
}

for (var s=0;s<35;s++){
	var page = {
		elements:[],
		lines:[],
		offsetX:0,
		offsetY:0,
		scale:1,
		sketchTitle:""
	};
	page.elements.push([11,6,s]);
	scrapbook.push(page)

	for (var i=-1;i<2;i++){
		for (var j=-1;j<2;j++){	
			for (var lt=0;lt<2;lt++){	
				if (i===0&&j===0){
					continue;
				}
				var page = {
					elements:[],
					lines:[],
					offsetX:0,
					offsetY:0,
					scale:1,
					sketchTitle:""
				};

				var px = 11;
				var py = 6;

				var ox = 11+i;
				var oy = 6+j;
				page.lines.push([px,py,ox,oy,lt])

				page.elements.push([px,py,0])
				page.elements.push([ox,oy,s])

				scrapbook.push(page)
			}
		}
	}
}

var dat = JSON.stringify(scrapbook, null, 4)
fs.writeFileSync("dat/scrapbook/dictionarytemplate.json", dat);
console.log()