#!/usr/bin/env node

var fs 				= require('fs')
var glob 			= require('./js/orthoGlobals')
var canvasRender 	= require('./js/canvasRender')
var lib 			= require('./js/orthoLib')
var svgRender 		= require("./js/svgRender")
var intersects = require('line-segments-intersect');
var pad = require('pad-right');

var log=console.log

if (process.argv.length===2){
	console.log("USAGE: jsonstats INPUT")
	return
}

var inputFileName=""
var outputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i]
	if (inputFileName===""){
		inputFileName=t
	} else if (outputFileName===""){
		outputFileName=t
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".")		
	}
}

if (inputFileName==="")
{
	console.log("need to supply input file")
}


lib.loadFile(inputFileName,false)
var pstr=JSON.stringify(glob.page)
lib.FixPageLines();
var fstr=JSON.stringify(glob.page)
var linesgood=pstr===fstr
var cyclic = lib.IsCyclic();

var m=25;
log(pad("ELEMENTS:",m,' ')+glob.page.elements.length)
log(pad("LINES:",m,' ')+glob.page.lines.length)
log(pad("WELL-DIRECTED LINES:",m,' ')+linesgood)
log(pad("SELF-INTERSECTS:",m,' ')+lib.SelfIntersects())
log(pad("CYCLIC:",m,' ')+cyclic)
