#!/usr/bin/env node

var emoji = require('node-emoji');



var fs 				= require('fs')
var glob 			= require('./js/orthoGlobals')
var lib 			= require('./js/orthoLib')
var svgRender 		= require("./js/orthoTopology")
var print 		= require("./js/jsonPrinter")
var log=console.log

if (process.argv.length===2){
	console.log("USAGE: printOrtho [-ascii] [-noLines] FILENAME");
	return;
}

var asciiCharacters=false;
var skeleton=false;
var inputFileName=""
for (var i=2;i<process.argv.length;i++){
	var t = process.argv[i];
	if (t==="-ascii"){
		asciiCharacters=true;
	} else if (t==="-noLines"){
		skeleton=true;
	} else if (inputFileName===""){
		inputFileName=t;
	} else {
		console.log("Too many arguments. Unexpected argument \""+t+"\".");		
	}
}
/*
var symbols = [
	"■","▼","⌔","○","•",
	"⊚","◇","△","□","☆",
	"♧","⧉","🔒","ᗡ","👑",
	"👁","👄","👆","👂","🍴",
	"💭","👃","⌛️","⊿","🍌",
	"⬡","⬇","⌑","λ","✙",
	"☯","▣","⨸","🌀","📄"];
*/

if (inputFileName==="")
{
	console.log("need to supply input file");
}

lib.loadFile(inputFileName);
var str = print.Print(skeleton,asciiCharacters);
console.log(str)